Add packages

diff --git a/lib/packages/secrets b/lib/packages/secrets
--- a/lib/packages/secrets
+++ b/lib/packages/secrets
@@ -6,10 +6,21 @@ FILES=$(cat <<-END
 END
 )
 
+KEYS=$(cat <<-END
+1password
+END
+)
+
 install() {
   for file in $FILES
   do
     echo "Please copy over a correct file for: $file"
+    read -r
+  done
+
+  for key in $KEYS
+  do
+    echo "Please insert a correct key for: $key"
     read -r
   done
 }
@@ -18,7 +29,15 @@ verify() {
   for file in $FILES
   do
     if [ ! -f "$file" ]; then
-      echo "$file is missing"
+      error "file $file is missing"
+      exit 1
+    fi
+  done
+
+  for key in $KEYS
+  do
+    if ! pass | grep -q "$key"; then
+      error "key $key is missing"
       exit 1
     fi
   done
